/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { SnippetCodenames } from '../system/snippets.generated.js';
import type { Elements, Snippet } from '@kontent-ai/delivery-sdk';
import type { CoreType } from '../system/types.generated.js';
           
            /*
* Type representing codename of 'Metadata' snippet
*/
            export type MetadataSnippetCodename = keyof Pick<Record<SnippetCodenames, null>, "metadata_c70df4f4c">;

            /*
* Typeguard for codename of 'Metadata' snippet
*/
            export function isMetadataSnippetCodename(value: string | undefined | null): value is MetadataSnippetCodename {
                return typeof value === 'string' && value === ('metadata_c70df4f4c' satisfies MetadataSnippetCodename);
            }

/*
    * Metadata
    *
    * Id: c427aa24-df50-545b-8f7e-587f9d3acc59
* Codename: metadata_c70df4f4c
    */
export type MetadataSnippet = Snippet<MetadataSnippetElementCodenames,
{
/*
    * Meta title
    *
    * Codename: metadata_c70df4f4c__metadata__meta_title
* Id: f82be36b-fbf6-5bd6-a83b-3010a4e0725e
* External Id: 8acfdfe4-faa9-4e99-b6c6-552459a7ab50
* Type: text
* Required: true
    */
                readonly metadata_c70df4f4c__metadata__meta_title: Elements.TextElement;

/*
    * Meta description
    *
    * Codename: metadata_c70df4f4c__metadata__meta_description
* Id: be0e37e3-7e6c-5704-b7e8-1898a539cdd0
* External Id: 889bc592-f442-4e84-a66c-43a09b00fb9c
* Type: text
* Required: true
    */
                readonly metadata_c70df4f4c__metadata__meta_description: Elements.TextElement;

/*
    * Meta keywords
    *
    * Codename: metadata_c70df4f4c__metadata__meta_keywords
* Id: 247fc5d9-1ef8-5faa-8983-c3c59ee51202
* External Id: 314b6cbe-f42f-4de9-97f1-d7310b9c5605
* Type: text
* Required: false
    */
                readonly metadata_c70df4f4c__metadata__meta_keywords: Elements.TextElement;

/*
    * Include in Robots.txt
    *
    * Codename: metadata_c70df4f4c__metadata__robots
* Id: 9984d1f1-2f24-5bf9-b17a-684151058e59
* External Id: f313b101-3238-41c2-b1ea-93a2a027fb38
* Type: multiple_choice
* Required: false
    */
                readonly metadata_c70df4f4c__metadata__robots: Elements.MultipleChoiceElement<MetadataSnippetIncludeInRobotsTxtMultipleChoiceOptions>;}>;

/*
* Type representing all available element codenames for Metadata
*/
export type MetadataSnippetElementCodenames = 'metadata_c70df4f4c__metadata__meta_title' | 'metadata_c70df4f4c__metadata__meta_description' | 'metadata_c70df4f4c__metadata__meta_keywords' | 'metadata_c70df4f4c__metadata__robots';

export type MetadataSnippetIncludeInRobotsTxtMultipleChoiceOptions = 'yes' | 'no'

            