/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Common' collection
*/
            export type CommonCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "default">;

            /*
* Typeguard for codename of 'Common' collection
*/
            export function isCommonCollectionCodename(value: string | undefined | null): value is CommonCollectionCodename {
                return typeof value === 'string' && value === ('default' satisfies CommonCollectionCodename);
            }
            