/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Leagues - Rhode Island' collection
*/
            export type LeaguesRhodeIslandCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "leagues___rhode_island">;

            /*
* Typeguard for codename of 'Leagues - Rhode Island' collection
*/
            export function isLeaguesRhodeIslandCollectionCodename(value: string | undefined | null): value is LeaguesRhodeIslandCollectionCodename {
                return typeof value === 'string' && value === ('leagues___rhode_island' satisfies LeaguesRhodeIslandCollectionCodename);
            }
            