/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Leagues - New England Elite' collection
*/
            export type LeaguesNewEnglandEliteCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "leagues___new_england_elite">;

            /*
* Typeguard for codename of 'Leagues - New England Elite' collection
*/
            export function isLeaguesNewEnglandEliteCollectionCodename(value: string | undefined | null): value is LeaguesNewEnglandEliteCollectionCodename {
                return typeof value === 'string' && value === ('leagues___new_england_elite' satisfies LeaguesNewEnglandEliteCollectionCodename);
            }
            