/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Perfect Game' collection
*/
            export type PerfectGameCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "perfect_game">;

            /*
* Typeguard for codename of 'Perfect Game' collection
*/
            export function isPerfectGameCollectionCodename(value: string | undefined | null): value is PerfectGameCollectionCodename {
                return typeof value === 'string' && value === ('perfect_game' satisfies PerfectGameCollectionCodename);
            }
            