/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { ArticleType } from '../types/article-type.generated.js';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Article Layout' type
*/
            export type ArticleLayoutTypeCodename = keyof Pick<Record<TypeCodenames, null>, "article_layout">;

            /*
* Typeguard for codename of 'Article Layout' type
*/
            export function isArticleLayoutTypeCodename(value: string | undefined | null): value is ArticleLayoutTypeCodename {
                return typeof value === 'string' && value === ('article_layout' satisfies ArticleLayoutTypeCodename);
            }

/*
    * Article Layout
    *
    * Id: f311adda-e433-402d-8e7c-dd2747ba6d71
* Codename: article_layout
    */
export type ArticleLayoutType = IContentItem<
{
/*
    * Article Layout
    *
    * Codename: article_layout
* Id: fd725986-5e2d-4218-a00b-d5a42d77af8e
* Type: modular_content
* Required: false
* Allowed content types: article
    */
                readonly article_layout: Elements.LinkedItemsElement<ArticleType>;}, 
ArticleLayoutTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Article Layout
*/
export type ArticleLayoutTypeElementCodenames = 'article_layout';;

/*
    * Type guard for Article Layout
    *
    * Id: f311adda-e433-402d-8e7c-dd2747ba6d71
* Codename: article_layout
    */
export function isArticleLayoutType(item: IContentItem | undefined | null): item is ArticleLayoutType {
                return item?.system.type === ('article_layout' satisfies ArticleLayoutTypeCodename);
            };



            