/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { LinkType } from '../types/link-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Call to action' type
*/
            export type CallToActionTypeCodename = keyof Pick<Record<TypeCodenames, null>, "call_to_action">;

            /*
* Typeguard for codename of 'Call to action' type
*/
            export function isCallToActionTypeCodename(value: string | undefined | null): value is CallToActionTypeCodename {
                return typeof value === 'string' && value === ('call_to_action' satisfies CallToActionTypeCodename);
            }

/*
    * Call to action
    *
    * Id: aa0dda15-7a54-58df-acc0-a926ed835ec3
* Codename: call_to_action
* External Id: 6ce8b846-e05f-4a54-b686-576df0a84be2
    */
export type CallToActionType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: d3241e23-81e7-5642-b17d-75557606bac1
* External Id: e5298f11-7feb-48e1-bab4-d34fe6b8fe29
* Type: text
* Required: false
    */
                readonly title: Elements.TextElement;

/*
    * Subtitle
    *
    * Codename: subtitle
* Id: 448ae7b6-d834-593a-9cd3-9215e305ad69
* External Id: 145e00e7-0cb0-4f11-b5b9-b1405488a823
* Type: text
* Required: false
    */
                readonly subtitle: Elements.TextElement;

/*
    * Image
    *
    * Codename: image
* Id: 84813d21-ef3f-59be-a9d6-bcb06b0c01ed
* External Id: 2d0c72bf-7910-4b66-bbaa-2c7d21b80b62
* Type: asset
* Required: false
    */
                readonly image: Elements.AssetsElement;

/*
    * Action Type
    *
    * Codename: action_type
* Id: 310614c1-2297-5e0a-830d-9ade75469014
* External Id: 23525863-8b3d-47c0-937e-1142d0744481
* Type: multiple_choice
* Required: true
    */
                readonly action_type: Elements.MultipleChoiceElement<CallToActionTypeActionTypeMultipleChoiceOptions>;

/*
    * Action Label
    *
    * Codename: action_label
* Id: 44caa2cb-1c66-5880-9562-ab886ebf5a70
* External Id: b68ef531-2c19-4d92-bfb0-0c0d309e2047
* Type: text
* Required: false
    */
                readonly action_label: Elements.TextElement;

/*
    * Link
    *
    * Codename: link
* Id: 50e54c35-6bcb-51db-803e-96be29b97280
* External Id: 7bd0f3f2-1587-4335-8a2f-9a4ecbb8fbb7
* Type: modular_content
* Required: false
* Allowed content types: link_a0dbe3d92
    */
                readonly link: Elements.LinkedItemsElement<LinkType>;}, 
CallToActionTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Call to action
*/
export type CallToActionTypeElementCodenames = 'title' | 'subtitle' | 'image' | 'action_type' | 'action_label' | 'link';;

/*
    * Type guard for Call to action
    *
    * Id: aa0dda15-7a54-58df-acc0-a926ed835ec3
* Codename: call_to_action
* External Id: 6ce8b846-e05f-4a54-b686-576df0a84be2
    */
export function isCallToActionType(item: IContentItem | undefined | null): item is CallToActionType {
                return item?.system.type === ('call_to_action' satisfies CallToActionTypeCodename);
            };

export type CallToActionTypeActionTypeMultipleChoiceOptions = 'button' | 'carousel' | 'callout' | 'infographic'

            