/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { AddressType } from '../types/address-type.generated.js';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { LinkType } from '../types/link-type.generated.js';
import type { MetadataSnippet } from '../snippets/metadata-snippet.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Contact' type
*/
            export type ContactTypeCodename = keyof Pick<Record<TypeCodenames, null>, "contact">;

            /*
* Typeguard for codename of 'Contact' type
*/
            export function isContactTypeCodename(value: string | undefined | null): value is ContactTypeCodename {
                return typeof value === 'string' && value === ('contact' satisfies ContactTypeCodename);
            }

/*
    * Contact
    *
    * Id: caf5447f-d85e-5116-b8bd-12d067ae9b51
* Codename: contact
* External Id: 57a580de-b8f4-4eca-aa54-86a4aa418942
    */
export type ContactType = IContentItem<
{
/*
    * Name
    *
    * Codename: name
* Id: 98a6c7c2-dcbc-5eba-a5cc-c8cf9aa480b3
* External Id: be2ad2f3-6fd4-4c42-9164-fbc151abbef9
* Type: text
* Required: true
    */
                readonly name: Elements.TextElement;

/*
    * Image
    *
    * Codename: image
* Id: c327d598-0edf-5543-be67-c6a531b5f31b
* External Id: 5901494c-a422-4010-8e7a-1f210ecdcab7
* Type: asset
* Required: false
    */
                readonly image: Elements.AssetsElement;

/*
    * Description
    *
    * Codename: description
* Id: d7df0d79-5a71-504b-8c4c-d379afbfdd22
* External Id: 4710a7e6-5cc7-4727-ab89-970a18cd88d6
* Type: rich_text
* Required: false
    */
                readonly description: Elements.RichTextElement<CoreType>;

/*
    * Address
    *
    * Codename: address
* Id: 28a75a7e-a889-5e0e-a1eb-d36aadeff19b
* External Id: b9578c7f-0385-4538-a7a8-3e55d66840b9
* Type: modular_content
* Required: false
* Allowed content types: address
    */
                readonly address: Elements.LinkedItemsElement<AddressType>;

/*
    * Email
    *
    * Codename: email
* Id: 2deb4ed5-a2d3-553f-bee2-a8adbd0b4bfd
* External Id: 43d39e01-512b-4d9a-be47-d2263d43461a
* Type: text
* Required: false
    */
                readonly email: Elements.TextElement;

/*
    * Phone
    *
    * Codename: phone
* Id: c9e83663-3b6d-5307-b706-b42eb755f391
* External Id: 58f3b69f-e07e-4001-ad96-07e55ce7b528
* Type: text
* Required: false
    */
                readonly phone: Elements.TextElement;

/*
    * Website
    *
    * Codename: website
* Id: f947b05d-daa8-5c45-a680-1c2adedc0c43
* External Id: cbdbc96d-ba3d-485b-acde-f1ab3eecfb8d
* Type: modular_content
* Required: false
* Allowed content types: link_a0dbe3d92
    */
                readonly website: Elements.LinkedItemsElement<LinkType>;} & MetadataSnippet, 
ContactTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Contact
*/
export type ContactTypeElementCodenames = 'name' | 'image' | 'description' | 'address' | 'email' | 'phone' | 'website' | 'metadata_c70df4f4c__metadata__meta_title' | 'metadata_c70df4f4c__metadata__meta_description' | 'metadata_c70df4f4c__metadata__meta_keywords' | 'metadata_c70df4f4c__metadata__robots';;

/*
    * Type guard for Contact
    *
    * Id: caf5447f-d85e-5116-b8bd-12d067ae9b51
* Codename: contact
* External Id: 57a580de-b8f4-4eca-aa54-86a4aa418942
    */
export function isContactType(item: IContentItem | undefined | null): item is ContactType {
                return item?.system.type === ('contact' satisfies ContactTypeCodename);
            };

export type ContactTypeIncludeInRobotsTxtMultipleChoiceOptions = 'yes' | 'no'

            