/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { PageType } from '../types/page-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Event Navigation' type
*/
            export type EventNavigationTypeCodename = keyof Pick<Record<TypeCodenames, null>, "event_navigation">;

            /*
* Typeguard for codename of 'Event Navigation' type
*/
            export function isEventNavigationTypeCodename(value: string | undefined | null): value is EventNavigationTypeCodename {
                return typeof value === 'string' && value === ('event_navigation' satisfies EventNavigationTypeCodename);
            }

/*
    * Event Navigation
    *
    * Id: 2e0f0167-d18d-43d3-a7aa-67c14435a472
* Codename: event_navigation
    */
export type EventNavigationType = IContentItem<
{
/*
    * Event Navigation
    *
    * Codename: event_navigation
* Id: d2940484-8fd9-4b73-96e9-cb00a650a729
* Type: subpages
* Required: false
* Allowed content types: page
    */
                readonly event_navigation: Elements.LinkedItemsElement<PageType>;}, 
EventNavigationTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Event Navigation
*/
export type EventNavigationTypeElementCodenames = 'event_navigation';;

/*
    * Type guard for Event Navigation
    *
    * Id: 2e0f0167-d18d-43d3-a7aa-67c14435a472
* Codename: event_navigation
    */
export function isEventNavigationType(item: IContentItem | undefined | null): item is EventNavigationType {
                return item?.system.type === ('event_navigation' satisfies EventNavigationTypeCodename);
            };



            