/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { ContactType } from '../types/contact-type.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { EventTypeTaxonomyTermCodenames, EventTypeTaxonomyCodename } from '../taxonomies/event-type-taxonomy.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { MetadataSnippet } from '../snippets/metadata-snippet.generated.js';
import type { OrganizationType } from '../types/organization-type.generated.js';
import type { VideoType } from '../types/video-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Event' type
*/
            export type EventTypeCodename = keyof Pick<Record<TypeCodenames, null>, "event">;

            /*
* Typeguard for codename of 'Event' type
*/
            export function isEventTypeCodename(value: string | undefined | null): value is EventTypeCodename {
                return typeof value === 'string' && value === ('event' satisfies EventTypeCodename);
            }

/*
    * Event
    *
    * Id: 4672eebe-5609-57f3-a127-af6282241ab2
* Codename: event
* External Id: a7b3d07e-d9e4-4909-8ffb-c990e77662cb
    */
export type EventType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: 9d6ad793-e84c-5268-b49c-d48fec0c090c
* External Id: 64b34baf-d48f-48f6-b528-e0944b0178f6
* Type: text
* Required: false
    */
                readonly title: Elements.TextElement;

/*
    * Image
    *
    * Codename: image
* Id: f5f03c8a-2557-5f8a-a546-6e56c0cc82b9
* External Id: 847f1366-8664-44d2-ba71-adf1e55d1898
* Type: asset
* Required: false
    */
                readonly image: Elements.AssetsElement;

/*
    * Video
    *
    * Codename: video
* Id: f2b60d0f-2272-5627-ae9d-2dda4cdff475
* External Id: 32d5be25-f16e-41cf-99f6-a44331714bc3
* Type: modular_content
* Required: false
* Allowed content types: video
    */
                readonly video: Elements.LinkedItemsElement<VideoType>;

/*
    * Start Date
    *
    * Codename: start_date
* Id: 9d9c9fe2-5b27-58b9-a012-5456ab3a4b52
* External Id: a0c8d46e-7721-4bb8-b5db-2c0b60808d43
* Type: date_time
* Required: true
    */
                readonly start_date: Elements.DateTimeElement;

/*
    * End Date
    *
    * Codename: end_date
* Id: 0c10c9ee-e755-564d-a6a0-875a0305978d
* External Id: 4b030fd6-2df2-44d8-9758-289a44cc7fcc
* Type: date_time
* Required: false
    */
                readonly end_date: Elements.DateTimeElement;

/*
    * Description
    *
    * Codename: description
* Id: e542eeb4-fdbd-5f96-804e-6b25b348b713
* External Id: a9adf14d-438b-4001-adab-c975670f7c41
* Type: rich_text
* Required: false
    */
                readonly description: Elements.RichTextElement<CoreType>;

/*
    * Average duration
    *
    * Codename: average_duration
* Id: 9651ddd9-1fee-5e40-831f-abc6b4b1d065
* External Id: a6f98d26-3c70-4ac6-a25e-714c74851fc3
* Type: text
* Required: false
    */
                readonly average_duration: Elements.TextElement;

/*
    * Event Type
    *
    * Codename: event_type
* Id: 942bbae5-8e45-55ac-9610-2698162db659
* External Id: 70895b17-ffb2-4296-963c-5d1fb70ace1c
* Type: taxonomy
* Required: true
* Taxonomy: event_type
    */
                readonly event_type: Elements.TaxonomyElement<EventTypeTaxonomyTermCodenames, EventTypeTaxonomyCodename>;

/*
    * Organizer
    *
    * Codename: organizer
* Id: 38f48bcb-cce7-5165-9cbb-3a6d97e2f506
* External Id: 29dcc1cb-7cd1-49fe-995b-491e4e67973e
* Type: modular_content
* Required: false
* Allowed content types: organization
    */
                readonly organizer: Elements.LinkedItemsElement<OrganizationType>;

/*
    * Location
    *
    * Codename: location
* Id: 057c3ec5-4a43-5b65-8f83-5abf15eaeab9
* External Id: 9bc196e3-e02b-48bf-bd52-cece51e3ea0c
* Type: modular_content
* Required: false
* Allowed content types: contact
    */
                readonly location: Elements.LinkedItemsElement<ContactType>;

/*
    * Slug
    *
    * Codename: slug
* Id: 65bf3809-c992-5d22-be35-0f49597aaa55
* External Id: 6991a94d-aa0f-4d5a-9027-9c935a9281f5
* Type: url_slug
* Required: false
    */
                readonly slug: Elements.UrlSlugElement;} & MetadataSnippet, 
EventTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Event
*/
export type EventTypeElementCodenames = 'title' | 'image' | 'video' | 'start_date' | 'end_date' | 'description' | 'average_duration' | 'event_type' | 'organizer' | 'location' | 'slug' | 'metadata_c70df4f4c__metadata__meta_title' | 'metadata_c70df4f4c__metadata__meta_description' | 'metadata_c70df4f4c__metadata__meta_keywords' | 'metadata_c70df4f4c__metadata__robots';;

/*
    * Type guard for Event
    *
    * Id: 4672eebe-5609-57f3-a127-af6282241ab2
* Codename: event
* External Id: a7b3d07e-d9e4-4909-8ffb-c990e77662cb
    */
export function isEventType(item: IContentItem | undefined | null): item is EventType {
                return item?.system.type === ('event' satisfies EventTypeCodename);
            };

export type EventTypeIncludeInRobotsTxtMultipleChoiceOptions = 'yes' | 'no'

            