/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { ArticleType } from '../types/article-type.generated.js';
import type { CallToActionType } from '../types/call-to-action-type.generated.js';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { EventType } from '../types/event-type.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { PageType } from '../types/page-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Landing Page' type
*/
            export type LandingPageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "landing_page">;

            /*
* Typeguard for codename of 'Landing Page' type
*/
            export function isLandingPageTypeCodename(value: string | undefined | null): value is LandingPageTypeCodename {
                return typeof value === 'string' && value === ('landing_page' satisfies LandingPageTypeCodename);
            }

/*
    * Landing Page
    *
    * Id: 5fb1801f-bf08-4f37-a96b-6c32a5327e56
* Codename: landing_page
    */
export type LandingPageType = IContentItem<
{
/*
    * Headline
    *
    * Codename: headline
* Id: 74039f22-6138-4efa-9d8c-71ae78f9ccc2
* Type: text
* Required: true
    */
                readonly headline: Elements.TextElement;

/*
    * Subheadline
    *
    * Codename: subheadline
* Id: 3b45e6d6-abc5-4453-892a-0ce4bf089c5e
* Type: text
* Required: false
    */
                readonly subheadline: Elements.TextElement;

/*
    * Hero Image
    *
    * Codename: hero_image
* Id: 495bbfd1-3536-4363-b039-bd8c861f573e
* Type: asset
* Required: true
    */
                readonly hero_image: Elements.AssetsElement;

/*
    * Body Copy
    *
    * Codename: body_copy
* Id: c6c52197-1e0e-40d6-bccb-2002591e6c5e
* Type: rich_text
* Required: false
    */
                readonly body_copy: Elements.RichTextElement<CoreType>;

/*
    * Featured Content
    *
    * Codename: featured_content
* Id: 96fa67da-0bfe-45d7-9b43-e28c06f8050f
* Type: modular_content
* Required: false
* Allowed content types: call_to_action, event, article
    */
                readonly featured_content: Elements.LinkedItemsElement<CallToActionType | EventType | ArticleType>;

/*
    * Subpages
    *
    * Codename: subpages
* Id: 24b59582-d83f-4b9e-9204-353dbd380648
* Type: subpages
* Required: false
* Allowed content types: page
    */
                readonly subpages: Elements.LinkedItemsElement<PageType>;}, 
LandingPageTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Landing Page
*/
export type LandingPageTypeElementCodenames = 'headline' | 'subheadline' | 'hero_image' | 'body_copy' | 'featured_content' | 'subpages';;

/*
    * Type guard for Landing Page
    *
    * Id: 5fb1801f-bf08-4f37-a96b-6c32a5327e56
* Codename: landing_page
    */
export function isLandingPageType(item: IContentItem | undefined | null): item is LandingPageType {
                return item?.system.type === ('landing_page' satisfies LandingPageTypeCodename);
            };



            