/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Link' type
*/
            export type LinkTypeCodename = keyof Pick<Record<TypeCodenames, null>, "link_a0dbe3d92">;

            /*
* Typeguard for codename of 'Link' type
*/
            export function isLinkTypeCodename(value: string | undefined | null): value is LinkTypeCodename {
                return typeof value === 'string' && value === ('link_a0dbe3d92' satisfies LinkTypeCodename);
            }

/*
    * Link
    *
    * Id: df3675f7-045f-58cb-bc39-5ada1e4b0468
* Codename: link_a0dbe3d92
* External Id: cb132b30-f85a-48b7-9539-97b75cdc4235
    */
export type LinkType = IContentItem<
{
/*
    * Label
    *
    * Codename: label
* Id: 753b3b6a-dc38-5813-b3a4-3f2d9c758090
* External Id: e795c04b-6cba-4cbe-99d0-002c18dddce9
* Type: text
* Required: false
    */
                readonly label: Elements.TextElement;

/*
    * Icon
    *
    * Codename: icon
* Id: ecbbe866-b71b-57b5-9363-178bb459dc78
* External Id: efc49bd7-408d-4452-9c34-0c74bdafb509
* Type: asset
* Required: false
    */
                readonly icon: Elements.AssetsElement;

/*
    * Internal Link
    *
    * Codename: internal_link
* Id: 862662c6-f697-5ba6-9b51-91fefdecbaf4
* External Id: 0b14b497-7f01-45e2-9cc4-54aaf7cb63c7
* Type: modular_content
* Required: false
* Guidelines: Limit "Allowed content types" to types containing a URL Slug element.
    */
                readonly internal_link: Elements.LinkedItemsElement<CoreType>;

/*
    * External URL
    *
    * Codename: external_url
* Id: a4cdc321-bf2a-5ce1-8a95-ef9f598e700c
* External Id: 32ee9637-55f7-4d5e-87a3-2fcf7458ec01
* Type: text
* Required: false
    */
                readonly external_url: Elements.TextElement;

/*
    * Open in new window?
    *
    * Codename: open_in_new_window_
* Id: be957b03-43f5-583a-8750-44894b9312a2
* External Id: 47dcc11f-69ed-44fa-9501-0dfe47f9ec84
* Type: multiple_choice
* Required: false
    */
                readonly open_in_new_window_: Elements.MultipleChoiceElement<LinkTypeOpenInNewWindowMultipleChoiceOptions>;}, 
LinkTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Link
*/
export type LinkTypeElementCodenames = 'label' | 'icon' | 'internal_link' | 'external_url' | 'open_in_new_window_';;

/*
    * Type guard for Link
    *
    * Id: df3675f7-045f-58cb-bc39-5ada1e4b0468
* Codename: link_a0dbe3d92
* External Id: cb132b30-f85a-48b7-9539-97b75cdc4235
    */
export function isLinkType(item: IContentItem | undefined | null): item is LinkType {
                return item?.system.type === ('link_a0dbe3d92' satisfies LinkTypeCodename);
            };

export type LinkTypeOpenInNewWindowMultipleChoiceOptions = 'yes' | 'no'

            