/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Navigation' type
*/
            export type NavigationTypeCodename = keyof Pick<Record<TypeCodenames, null>, "navigation">;

            /*
* Typeguard for codename of 'Navigation' type
*/
            export function isNavigationTypeCodename(value: string | undefined | null): value is NavigationTypeCodename {
                return typeof value === 'string' && value === ('navigation' satisfies NavigationTypeCodename);
            }

/*
    * Navigation
    *
    * Id: fcc0fc11-c150-5127-8b8c-6b375325dcd4
* Codename: navigation
* External Id: af732d55-23ed-432b-9ee2-dd86864e439e
    */
export type NavigationType = IContentItem<
{
/*
    * Label
    *
    * Codename: label
* Id: e22b5e2e-1eef-56ba-8578-36de1a619c54
* External Id: 1fc9c296-c999-4ec8-a0b0-6b256d63cd46
* Type: text
* Required: false
    */
                readonly label: Elements.TextElement;

/*
    * Caption
    *
    * Codename: caption
* Id: 77629dc0-49d4-5660-8875-2ca4223cfb1a
* External Id: 09b309b1-7503-4a06-956d-5332681380d2
* Type: text
* Required: false
    */
                readonly caption: Elements.TextElement;

/*
    * Icon
    *
    * Codename: icon
* Id: dc5a4a36-91eb-53f6-a89a-a5abdab48aa7
* External Id: e2624bb8-7f95-4789-b3a7-1f9623ee95e9
* Type: asset
* Required: false
    */
                readonly icon: Elements.AssetsElement;

/*
    * Links
    *
    * Codename: links
* Id: 10c9f317-63fd-59a7-9934-912baab84bf0
* External Id: 0a5c6ec7-b4ca-4d24-b8bd-9eef9955ed36
* Type: modular_content
* Required: false
    */
                readonly links: Elements.LinkedItemsElement<CoreType>;

/*
    * Subnavigation
    *
    * Codename: subnavigation
* Id: c87100b0-1409-526c-91ad-2fd6e56023d9
* External Id: 7cb42ad8-55ec-499f-ae12-a66c46965e70
* Type: modular_content
* Required: false
* Allowed content types: navigation
    */
                readonly subnavigation: Elements.LinkedItemsElement<NavigationType>;}, 
NavigationTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Navigation
*/
export type NavigationTypeElementCodenames = 'label' | 'caption' | 'icon' | 'links' | 'subnavigation';;

/*
    * Type guard for Navigation
    *
    * Id: fcc0fc11-c150-5127-8b8c-6b375325dcd4
* Codename: navigation
* External Id: af732d55-23ed-432b-9ee2-dd86864e439e
    */
export function isNavigationType(item: IContentItem | undefined | null): item is NavigationType {
                return item?.system.type === ('navigation' satisfies NavigationTypeCodename);
            };



            