/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { ContactType } from '../types/contact-type.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { LinkType } from '../types/link-type.generated.js';
import type { MetadataSnippet } from '../snippets/metadata-snippet.generated.js';
import type { OrganizationTypeTaxonomyTermCodenames, OrganizationTypeTaxonomyCodename } from '../taxonomies/organization-type-taxonomy.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Organization' type
*/
            export type OrganizationTypeCodename = keyof Pick<Record<TypeCodenames, null>, "organization">;

            /*
* Typeguard for codename of 'Organization' type
*/
            export function isOrganizationTypeCodename(value: string | undefined | null): value is OrganizationTypeCodename {
                return typeof value === 'string' && value === ('organization' satisfies OrganizationTypeCodename);
            }

/*
    * Organization
    *
    * Id: 27d710b3-8f38-5b65-b831-7df365d08749
* Codename: organization
* External Id: 2081ad0b-3e0d-4924-845e-59ed0c36d7d2
    */
export type OrganizationType = IContentItem<
{
/*
    * Name
    *
    * Codename: name
* Id: 7da5da6a-77f5-567a-9313-c593be252261
* External Id: ccc532bb-9f7d-49e0-9727-8d06a47d8c6d
* Type: text
* Required: true
    */
                readonly name: Elements.TextElement;

/*
    * Image
    *
    * Codename: image
* Id: a6184dd4-8e84-556e-8c82-d85c590ec4b7
* External Id: 34a51b7a-772f-407a-88f3-676bf2a905a9
* Type: asset
* Required: false
    */
                readonly image: Elements.AssetsElement;

/*
    * Description
    *
    * Codename: description
* Id: a6e7f0d9-58ab-56f7-a94b-43c6266ebeff
* External Id: f883c392-4bff-4d50-a790-859e74442b9a
* Type: rich_text
* Required: false
    */
                readonly description: Elements.RichTextElement<CoreType>;

/*
    * Contact
    *
    * Codename: contact
* Id: b6af8be6-8120-5a71-b4f3-8ee1c101c793
* External Id: aaf8fbff-6ccf-49e9-9e81-08f41aa5248f
* Type: modular_content
* Required: false
* Allowed content types: contact
    */
                readonly contact: Elements.LinkedItemsElement<ContactType>;

/*
    * Links
    *
    * Codename: links
* Id: 54912382-17c5-58d6-b3a3-d3fb9df0cad2
* External Id: 4df130af-dd0f-4c60-89a9-d6364da7a400
* Type: modular_content
* Required: false
* Allowed content types: link_a0dbe3d92
    */
                readonly links: Elements.LinkedItemsElement<LinkType>;

/*
    * Organization Type
    *
    * Codename: organization_type
* Id: cfe0a19f-df1e-50c5-95e5-b97038c3ee4f
* External Id: 5b7ff4a9-6b10-4762-b315-65037fe50b28
* Type: taxonomy
* Required: false
* Taxonomy: organization_type
    */
                readonly organization_type: Elements.TaxonomyElement<OrganizationTypeTaxonomyTermCodenames, OrganizationTypeTaxonomyCodename>;} & MetadataSnippet, 
OrganizationTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Organization
*/
export type OrganizationTypeElementCodenames = 'name' | 'image' | 'description' | 'contact' | 'links' | 'organization_type' | 'metadata_c70df4f4c__metadata__meta_title' | 'metadata_c70df4f4c__metadata__meta_description' | 'metadata_c70df4f4c__metadata__meta_keywords' | 'metadata_c70df4f4c__metadata__robots';;

/*
    * Type guard for Organization
    *
    * Id: 27d710b3-8f38-5b65-b831-7df365d08749
* Codename: organization
* External Id: 2081ad0b-3e0d-4924-845e-59ed0c36d7d2
    */
export function isOrganizationType(item: IContentItem | undefined | null): item is OrganizationType {
                return item?.system.type === ('organization' satisfies OrganizationTypeCodename);
            };

export type OrganizationTypeIncludeInRobotsTxtMultipleChoiceOptions = 'yes' | 'no'

            