/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Roster' type
*/
            export type RosterTypeCodename = keyof Pick<Record<TypeCodenames, null>, "roster">;

            /*
* Typeguard for codename of 'Roster' type
*/
            export function isRosterTypeCodename(value: string | undefined | null): value is RosterTypeCodename {
                return typeof value === 'string' && value === ('roster' satisfies RosterTypeCodename);
            }

/*
    * Roster
    *
    * Id: b51fc32e-acbd-49d7-ba9a-f6db464ea92d
* Codename: roster
    */
export type RosterType = IContentItem<
Record<string, never>, 
RosterTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Roster
*/
export type RosterTypeElementCodenames = never;

/*
    * Type guard for Roster
    *
    * Id: b51fc32e-acbd-49d7-ba9a-f6db464ea92d
* Codename: roster
    */
export function isRosterType(item: IContentItem | undefined | null): item is RosterType {
                return item?.system.type === ('roster' satisfies RosterTypeCodename);
            };



            