/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { OrganizationType } from '../types/organization-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Testimonial' type
*/
            export type TestimonialTypeCodename = keyof Pick<Record<TypeCodenames, null>, "testimonial">;

            /*
* Typeguard for codename of 'Testimonial' type
*/
            export function isTestimonialTypeCodename(value: string | undefined | null): value is TestimonialTypeCodename {
                return typeof value === 'string' && value === ('testimonial' satisfies TestimonialTypeCodename);
            }

/*
    * Testimonial
    *
    * Id: a75b75ba-1e09-5846-9876-687d50890348
* Codename: testimonial
* External Id: 0d2a5f0d-8fd8-453d-89a5-0b367b08e746
    */
export type TestimonialType = IContentItem<
{
/*
    * Quote
    *
    * Codename: quote
* Id: 9d783451-f842-5a81-861a-e019796e104e
* External Id: 4596c801-16c5-42e4-b9ca-9a4200d875aa
* Type: rich_text
* Required: true
* Guidelines: Make sure to use quotation marks
    */
                readonly quote: Elements.RichTextElement<CoreType>;

/*
    * Name
    *
    * Codename: subtitle
* Id: 3e43c10a-6cd8-51de-881e-e10a0a9e4597
* External Id: ad65eb64-274b-4d66-b380-ddc7a9e5382a
* Type: text
* Required: true
* Guidelines: Who said the quote
    */
                readonly subtitle: Elements.TextElement;

/*
    * Title/Accomplishment
    *
    * Codename: title_14106ff
* Id: 14106ff5-c133-4d0e-82a9-661ab352d0b1
* Type: text
* Required: false
* Guidelines: What was their most prominent role in any organization, or accomplishment (MVP, ROY)
    */
                readonly title_14106ff: Elements.TextElement;

/*
    * Organization
    *
    * Codename: organization
* Id: 3bdbc8c1-38cc-4f1d-b30c-ca9614f7e3fe
* Type: modular_content
* Required: true
* Allowed content types: organization
    */
                readonly organization: Elements.LinkedItemsElement<OrganizationType>;}, 
TestimonialTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Testimonial
*/
export type TestimonialTypeElementCodenames = 'quote' | 'subtitle' | 'title_14106ff' | 'organization';;

/*
    * Type guard for Testimonial
    *
    * Id: a75b75ba-1e09-5846-9876-687d50890348
* Codename: testimonial
* External Id: 0d2a5f0d-8fd8-453d-89a5-0b367b08e746
    */
export function isTestimonialType(item: IContentItem | undefined | null): item is TestimonialType {
                return item?.system.type === ('testimonial' satisfies TestimonialTypeCodename);
            };



            