/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { LanguageCodenames } from '../system/languages.generated.js';
           
            /*
* Type representing codename of 'Default project language' language
*/
            export type DefaultProjectLanguageLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "default">;

            /*
* Typeguard for codename of 'Default project language' language
*/
            export function isDefaultProjectLanguageLanguageCodename(value: string | undefined | null): value is DefaultProjectLanguageLanguageCodename {
                return typeof value === 'string' && value === ('default' satisfies DefaultProjectLanguageLanguageCodename);
            }
            