/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Category' taxonomy
*/
            export type CategoryTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "category_f30035fd1">;

            /*
* Typeguard for codename of 'Category' taxonomy
*/
            export function isCategoryTaxonomyCodename(value: string | undefined | null): value is CategoryTaxonomyCodename {
                return typeof value === 'string' && value === ('category_f30035fd1' satisfies CategoryTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const categoryTaxonomyTermCodenames = ['technology_and_innovation', 'health_and_wellness', 'business_and_finance', 'lifestyle_and_culture', 'science_and_environment', 'education_and_learning'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type CategoryTaxonomyTermCodenames = typeof categoryTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isCategoryTaxonomyTermCodename(value: string | undefined | null): value is CategoryTaxonomyTermCodenames {
                return typeof value === 'string' && (categoryTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            