/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Event Type' taxonomy
*/
            export type EventTypeTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "event_type">;

            /*
* Typeguard for codename of 'Event Type' taxonomy
*/
            export function isEventTypeTaxonomyCodename(value: string | undefined | null): value is EventTypeTaxonomyCodename {
                return typeof value === 'string' && value === ('event_type' satisfies EventTypeTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const eventTypeTaxonomyTermCodenames = ['webinar', 'training', 'conference', 'seminar', 'fundraiser', 'launch'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type EventTypeTaxonomyTermCodenames = typeof eventTypeTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isEventTypeTaxonomyTermCodename(value: string | undefined | null): value is EventTypeTaxonomyTermCodenames {
                return typeof value === 'string' && (eventTypeTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            