/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Organization Type' taxonomy
*/
            export type OrganizationTypeTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "organization_type">;

            /*
* Typeguard for codename of 'Organization Type' taxonomy
*/
            export function isOrganizationTypeTaxonomyCodename(value: string | undefined | null): value is OrganizationTypeTaxonomyCodename {
                return typeof value === 'string' && value === ('organization_type' satisfies OrganizationTypeTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const organizationTypeTaxonomyTermCodenames = ['manufacturer', 'partner', 'provider', 'highschool_team'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type OrganizationTypeTaxonomyTermCodenames = typeof organizationTypeTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isOrganizationTypeTaxonomyTermCodename(value: string | undefined | null): value is OrganizationTypeTaxonomyTermCodenames {
                return typeof value === 'string' && (organizationTypeTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            