/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Role' taxonomy
*/
            export type RoleTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "role">;

            /*
* Typeguard for codename of 'Role' taxonomy
*/
            export function isRoleTaxonomyCodename(value: string | undefined | null): value is RoleTaxonomyCodename {
                return typeof value === 'string' && value === ('role' satisfies RoleTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const roleTaxonomyTermCodenames = ['scout', 'event_organizer', 'regional_admin', 'manager', 'writer'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type RoleTaxonomyTermCodenames = typeof roleTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isRoleTaxonomyTermCodename(value: string | undefined | null): value is RoleTaxonomyTermCodenames {
                return typeof value === 'string' && (roleTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            