/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { WorkflowCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Article' workflow
*/
            export type ArticleWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "article">;

            /*
* Typeguard for codename of 'Article' workflow
*/
            export function isArticleWorkflowCodename(value: string | undefined | null): value is ArticleWorkflowCodename {
                return typeof value === 'string' && value === ('article' satisfies ArticleWorkflowCodename);
            }

            /*
* Array of all workflow step codenames
*/
            export const articleWorkflowStepCodenames = ['draft_71dae29', 'review', 'published', 'archived', 'scheduled'] as const;;
           
            /*
* Type representing all workflow step codenames
*/
            export type ArticleWorkflowStepCodenames = typeof articleWorkflowStepCodenames[number];;

            /*
* Typeguard for workflow step codename
*/
            export function isArticleWorkflowStepCodename(value: string | undefined | null): value is ArticleWorkflowStepCodenames {
                return typeof value === 'string' && (articleWorkflowStepCodenames as readonly string[]).includes(value);
            };
            