/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            import type { WorkflowCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Event Workflow' workflow
*/
            export type EventWorkflowWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "event_workflow">;

            /*
* Typeguard for codename of 'Event Workflow' workflow
*/
            export function isEventWorkflowWorkflowCodename(value: string | undefined | null): value is EventWorkflowWorkflowCodename {
                return typeof value === 'string' && value === ('event_workflow' satisfies EventWorkflowWorkflowCodename);
            }

            /*
* Array of all workflow step codenames
*/
            export const eventWorkflowWorkflowStepCodenames = ['draft_ae09558', 'review_ceea643', 'confirmation_from_payment_team', 'published', 'archived', 'scheduled'] as const;;
           
            /*
* Type representing all workflow step codenames
*/
            export type EventWorkflowWorkflowStepCodenames = typeof eventWorkflowWorkflowStepCodenames[number];;

            /*
* Typeguard for workflow step codename
*/
            export function isEventWorkflowWorkflowStepCodename(value: string | undefined | null): value is EventWorkflowWorkflowStepCodenames {
                return typeof value === 'string' && (eventWorkflowWorkflowStepCodenames as readonly string[]).includes(value);
            };
            