/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all element codenames
*/
            export const elementCodenames = ['event_navigation', 'title', 'subtitle', 'image', 'action_type', 'action_label', 'link', 'video', 'start_date', 'end_date', 'description', 'average_duration', 'event_type', 'organizer', 'location', 'slug', 'metadata_c70df4f4c__metadata__meta_title', 'metadata_c70df4f4c__metadata__meta_description', 'metadata_c70df4f4c__metadata__meta_keywords', 'metadata_c70df4f4c__metadata__robots', 'name', 'projected_class', 'position', 'hometown', 'headline', 'subheadline', 'hero_image', 'body', 'url', 'subpages', 'asset', 'caption', 'alternate_text', 'category', 'label', 'icon', 'internal_link', 'external_url', 'open_in_new_window_', 'video_link', 'links', 'subnavigation', 'event_information_body', 'event_information_image', 'event_results', 'event_most_valuable_player', 'event_most_valuable_pitcher', 'contact', 'address', 'email', 'phone', 'website', 'country', 'street', 'suite', 'city', 'state', 'zip', 'latitude', 'longitude', 'first_name', 'last_name', 'prefix', 'biography', 'job_title', 'role', 'organization_type', 'body_copy', 'featured_content', 'quote', 'title_14106ff', 'organization', 'summary', 'date', 'author', 'tags', 'article_layout'] as const;;
           
            /*
* Type representing all element codenames
*/
            export type ElementCodenames = typeof elementCodenames[number];;

            /*
* Typeguard for element codename
*/
            export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
                return typeof value === 'string' && (elementCodenames as readonly string[]).includes(value);
            };