/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all language codenames
*/
            export const languageCodenames = ['default'] as const;;
           
            /*
* Type representing all language codenames
*/
            export type LanguageCodenames = typeof languageCodenames[number];;

            /*
* Typeguard for language codename
*/
            export function isLanguageCodename(value: string | undefined | null): value is LanguageCodenames {
                return typeof value === 'string' && (languageCodenames as readonly string[]).includes(value);
            };