/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all snippet codenames
*/
            export const snippetCodenames = ['metadata_c70df4f4c'] as const;;
           
            /*
* Type representing all snippet codenames
*/
            export type SnippetCodenames = typeof snippetCodenames[number];;

            /*
* Typeguard for snippet codename
*/
            export function isSnippetCodename(value: string | undefined | null): value is SnippetCodenames {
                return typeof value === 'string' && (snippetCodenames as readonly string[]).includes(value);
            };