/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all taxonomy codenames
*/
            export const taxonomyCodenames = ['event_type', 'organization_type', 'role', 'category_f30035fd1'] as const;;
           
            /*
* Type representing all taxonomy codenames
*/
            export type TaxonomyCodenames = typeof taxonomyCodenames[number];;

            /*
* Typeguard for taxonomy codename
*/
            export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
                return typeof value === 'string' && (taxonomyCodenames as readonly string[]).includes(value);
            };