/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: ⚾ Perfect Game
 * Environment: Production
 * Id: 9609eaef-6582-007e-452c-3b671b800257
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all workflow codenames
*/
            export const workflowCodenames = ['default', 'article', 'event_workflow'] as const;;
           
            /*
* Type representing all workflow codenames
*/
            export type WorkflowCodenames = typeof workflowCodenames[number];;

            /*
* Typeguard for workflow codename
*/
            export function isWorkflowCodename(value: string | undefined | null): value is WorkflowCodenames {
                return typeof value === 'string' && (workflowCodenames as readonly string[]).includes(value);
            };

            /*
* Array of all workflow codenames
*/
            export const workflowStepCodenames = ['draft', 'published', 'archived', 'scheduled', 'draft_71dae29', 'review', 'draft_ae09558', 'review_ceea643', 'confirmation_from_payment_team'] as const;;
           
            /*
* Type representing all workflow codenames
*/
            export type WorkflowStepCodenames = typeof workflowStepCodenames[number];;

            /*
* Typeguard for workflow codename
*/
            export function isWorkflowStepCodename(value: string | undefined | null): value is WorkflowStepCodenames {
                return typeof value === 'string' && (workflowStepCodenames as readonly string[]).includes(value);
            };